### PR TITLE
Fixing #433 - instance should inherit defaults

### PR DESCRIPTION
**Pull request by yanivefraim**
https://github.com/mzabriskie/axios/issues/443

### CODE REVIEW

**Comment by yanivefraim** [comment]
Question - do we want defaults to affect instances *after* instance was created? 
For example - I create an instance using default 'a'. Then I change this default to be 'b'. Do I want my instance to change accordingly?

**Comment by nickuraltsev** [comment]
@yanivefraim Good question! I think changing `defaults` should affect at least the default instance. For example:

```js
defaults.baseURL = 'http://foo.com/';
axios.get('/user');

defaults.baseURL = 'http://bar.com/';
axios.get('/user');  // should make a request to http://bar.com/user
```

If we do so for the default instance, we should probably do the same for custom instances for consistency. Does it make sense?

Thank you for your help!

**Comment by yanivefraim** [comment]
@nickuraltsev - IMO when you create an instance with specific defaults it will be confusing / not predictable if those defaults will be changed later when someone is changing the main defaults... And what if I already changed my instance's defaults? Then I would definitely not want those to be changed!

**Comment by nickuraltsev** [comment]
I'm not sure about this. Applying instance defaults changes, but ignoring global defaults changes seems confusing too. For example:

```js
const instance = axios.create();

instance.defaults.timeout =123;
instance.get('/foo'); // the new timeout will be used

defaults.validateStatus = status => true; // all statuses are ok
instance.get('/foo'); // should new validateStatus be used?
```

**Comment by yanivefraim** [comment]
I agree. Anyway, it should be well documented, and I will be happy to implement whatever you guys decide...

**Comment by matheus208** [comment]
Is there a plan to merge this?

This makes testing apps that use `axios.create()` SO much easier using `axios-mock-adapter`.

**Comment by matheus208** [comment]
Regarding syncing the default and custom instance configs: I agree with @yanivefraim. Once you create a new instance, I wouldn't expect its configs to change if I change the defaults.

**Comment by yanivefraim** [comment]
I think that those [issues](https://github.com/mzabriskie/axios/projects/1) are critical, it is a show stopper for us. Mainly https://github.com/mzabriskie/axios/issues/385, which can create a mess in your requests. I'll be happy to help and fix those, but we must have a decision from maintainers.
cc @nickuraltsev @mzabriskie

**Comment by nickuraltsev** [comment]
@yanivefraim Thanks a lot for your help! I've been busy, but I'll review your PRs and get back you soon.

**Comment by yanivefraim** [comment]
Cool. I would really love to be involved and contribute here. I think you / we should consider refactoring defaults mechanism, due to all of those issues

**Comment by nickuraltsev** [comment]
@yanivefraim What if we make `axios.defaults` a reference to the global defaults object (exported by `lib/defaults.js`) instead of creating a new object? Custom instances already use the global defaults when sending a request, so everything will work as designed.

```js
// change the global defaults before creating an instance
axios.defaults.timeout = 100;

const instance = axios.create();
instance.get('/foo'); // timeout is 100

// change the global defaults after creating the instance
axios.defaults.timeout = 200;
instance.get('/foo'); // timeout is 200 because the global defaults are merged in request()

// also, we can override anything at the instance level
instance.defaults = 300;
instance.get('/foo'); // timeout is 300 because the instance defaults take precedence over the global defaults
```

Thoughts?

**Comment by nickuraltsev** [comment]
Closed by mistake

**Comment by yanivefraim** [comment]
@nickuraltsev - I fixed the PR according to your idea. 

Another thing that might consider is exposing global defaults, something like:

`axios.GLOBAL_DEFAULTS` or  `axios.global_defaults`, so we'll have axios as a default instance on one hand, and as an api on the other hand (including `axios.Cancel`, `CancelToken` and so on, and including the new `axios.global_defaults`). This might prevent confusion between axios default instance defaults and global defaults.

WDYT?

**Comment by yanivefraim** [comment]
ping... ? 
@nickuraltsev @mzabriskie

**Comment by nickuraltsev** [comment]
What's the reason for replacing the default instance's config with `defaults` after the default instance is created? Can we pass the correct config to the constructor instead (for the default and custom instances)?

**Comment by nickuraltsev** [comment]
Closing in favor of 6d0e19343a6180fb8f5c50d843dd15feeb1f49f3

**Pull request closed without merging**
