### PR TITLE
XDomainRequest support

### PR DESCRIPTION
**Pull request by vineethawal**

### CODE REVIEW

**Comment by vineethawal** [comment]
Closes #131

**Comment by inuscript** [comment]
+1

**Comment by vineethawal** [comment]
@mzabriskie if the PR looks good can you have it merged?

**Comment by ldabiralai** [comment]
Good job! Any news on when this'll be merged?

Looking to use it in a project without having to reference the commit hash.

**Comment by vineethawal** [comment]
@mzabriskie can we have this merged? we are waiting to use this feature in our project.

**Comment by mzabriskie** [comment]
Sorry, I thought that I had replied to this already.

A couple changes need to be made, but overall I like the solution.

- Don't commit the `dist/` files
- Resolve merge conflicts (probably just rebase on master)
- Don't make XDomain a config option. This should be transparent to the user. Let's have axios handle the logic internally.

```js
// This would go at the top of lib/adapters/xhr.js
var isURLSameOrigin = require('./../helpers/isURLSameOrigin');

// Slight modification to your code
var adapter = (XMLHttpRequest || ActiveXObject);
var loadEvent = 'onreadystatechange';
var xDomain = false;

// For IE 8/9 CORS support
if (!isURLSameOrigin(config.url) && window.XDomainRequest) {
  adapter = window.XDomainRequest;
  loadEvent = 'onload';
  xDomain = true;
}
```

**Comment by mzabriskie** [comment]
There was a failing test on master when you merged. I have fixed the test. Please try merging master into your branch again.

**Comment by vineethawal** [comment]
Done!

**Pull request merged**
