### PR TITLE
Expose XHR instance

### PR DESCRIPTION
**Pull request by AurelioDeRosa**
Fixes gh-64

### CODE REVIEW

**Comment by AurelioDeRosa** [comment]
Hi @mzabriskie.

I hate to have to ask this, but could you take a look at this PR? We (the team behind [Github.js](https://github.com/michael/github)) have switched to axios for our requests and this is the only piece left for the new release. In the previous versions we exposed the XHR istance, so not having it would cause a breaking change.

**Comment by AurelioDeRosa** [comment]
Any chance to review this PR so that we can address #214?

**Comment by clayreimann** [comment]
@mzabriskie ping.

**Comment by mzabriskie** [comment]
@AurelioDeRosa I'm fine merging this, but will you please do the same for the `http` adapter?

**Comment by AurelioDeRosa** [comment]
@mzabriskie is `req` the object you want to return in the http adapter?

**Comment by mzabriskie** [comment]
@AurelioDeRosa sorry, I just saw your response. Yes, `req` would be the object to use.

**Comment by AurelioDeRosa** [comment]
@mzabriskie Applied the change and also rebased.

**Pull request merged**
