### PR TITLE
Fixing issue with Travis

### LINKED ISSUE #273: All PR builds fail due to Travis security restrictions
From https://docs.travis-ci.com/user/encryption-keys/ :

"Please note that encrypted environment variables are not available for pull requests from forks."

Also, from https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests :

"If your build relies on these to run, for instance to run Selenium tests with Sauce Labs, your build needs to take this into account. You won’t be able to run these tests for pull requests from external contributors."

### PR DESCRIPTION
**Pull request by nickuraltsev**
Fixes #273

### CODE REVIEW

**Comment by mzabriskie** [comment]
Thank you so much for fixing this. I hadn't had a chance to look into it yet. Quick question: do we have to use PhantomJS on PR or can we use Firefox?

**Comment by nickuraltsev** [comment]
@mzabriskie Yes, looks like we can use Firefox. I will try it out tonight and update the PR.

**Comment by nickuraltsev** [comment]
It seems to work. I have updated the PR.

**Comment by mzabriskie** [comment]
Thanks for your help with this!

**Comment by nickuraltsev** [comment]
You are welcome!

**Pull request merged**
