### PR TITLE
Update to 0.9.1 axios

### PR DESCRIPTION
**Pull request by kant2002**
These typings copied from DT

### CODE REVIEW

**Comment by kant2002** [comment]
@mzabriskie Could you merge in? Having updated type definitions in NPM module allow not install custom type definitions, but outdated API declaration is big miss.

**Comment by mzabriskie** [comment]
Travis CI has been failing for all PRs. Let me figure out what's wrong, then we'll get this merged.

**Comment by mzabriskie** [comment]
Ok Travis/Saucelabs have been fixed. Will you rebase on master and let's try again?

**Comment by nickuraltsev** [comment]
Given that axios type definitions are available at DefinitelyTyped (https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/axios), does it really make sense to have them in this repository? I will submit a new issue to discuss this.

**Comment by nickuraltsev** [comment]
Please see #282

**Comment by nickuraltsev** [comment]
The definitions from DT don't seem to be completely accurate. For example, it suggests that `AxiosInstance` is a function which is not correct. Another issue is that `AxiosInstance` does not have `all` and `spread` methods. Also, I believe that axios interface names should not contain 'XHR' as it's just one of the adapters.

We can, of course, take these definitions as a base and then improve upon them. 

Another option is to merge #163 (which updates axios.d.ts to use the ES6 module syntax) and then add the missing parts (like Interceptors).

**Comment by nickuraltsev** [comment]
Closing in favor of #419.

**Pull request closed without merging**
