### PR TITLE
HTTP basic authentication.

### LINKED ISSUE #78: Support for basic authentication on XMLHttpRequest.open() ?
As far as I can see, Axios doesn't support easy basic authentication headers in XMLHttpRequest ([xhr.js L37]( https://github.com/mzabriskie/axios/blob/1629a026da17a1e1d8999a02f3fe6b6b60aaac9c/lib/adapters/xhr.js#L37)). The [open()](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#open()) method on XMLHttpRequest can take a username and password as the 4th and 5th argument, which is a lot easier than base64 encoding the "Authorization" header manually.

Am I missing something or is there a specific reason for this design choice?

### PR DESCRIPTION
**Pull request by lachenmayer**
Fixes #78.

I have not yet added any documentation/tests/etc, since I'd like to make sure you're happy with the approach.

I modelled the interface on [`request`'s basic auth](https://github.com/request/request#http-authentication), ie. adding an `auth` key to the config object, which can contain any combination of `user`/`username` and `pass`/`password`.

Thanks for creating axios, the codebase is very pleasant :)

### CODE REVIEW

**Comment by mzabriskie** [comment]
Thanks for this PR. Looks great. Please add tests, and docs, then I'll get it merged.

**Comment by dzannotti** [comment]
@mzabriskie any chances of getting this merged?

**Comment by mzabriskie** [comment]
@dzannotti yes, I intend to merge. @lachenmayer said that he would add some tests, and documentation first. Just waiting on that.

**Comment by lachenmayer** [comment]
Sorry, haven't gotten around to this yet, should be able to do that tomorrow!

**Comment by mzabriskie** [comment]
@lachenmayer any chance of getting this resolved? If not I'll do it myself.

**Comment by Chris911** [comment]
Any updates on this? Would be really useful.

**Comment by mzabriskie** [comment]
Closed in favor of #167

**Pull request closed without merging**
