### PR TITLE
abortOnRetry and proxy for http.js

### PR DESCRIPTION
**Pull request by msangui**
I took the liberty to build a "solution" for request abortion (e.g. autocomplete example)
And also add a proxy property for http.js (e.g. inside company's proxy)

### CODE REVIEW

**Comment by msangui** [comment]
bump, any comment?

**Comment by ericraio** [comment]
please merge the proxy option!

**Comment by nickuraltsev** [comment]
@msangui Thank you for the PR and sorry for the delay! Could you please submit a separate PR for the proxy feature? I will be happy to merge it. We have not decided on how to abort requests yet, so I would not mix these changes.

**Comment by nickuraltsev** [comment]
@msangui I've just merged the proxy related changes. Thank you again!

**Comment by so4pmaker** [comment]
How do we configure the proxy options?

**Comment by nickuraltsev** [comment]
@so4pmaker not yet. Hope it will be released soon. I'll also update the docs. In short, you just need to set `proxy` config parameter as follows:

```js
axios.defaults.proxy = {
  host: 'foobar.com',
  port: 8888
};
```
or
```js
axios.get(url, { proxy: { host: 'foobar.com', port: 8888 } });
```
or
```js
var instance = axios.create({ proxy: { host: 'foobar.com', port: 8888 } });
```

**Comment by msangui** [comment]
great to see this merged :D

If you need any help/ideas on aborting count me in.

**Comment by gajus** [comment]
Is this still not in the `./dist`?

**Comment by msangui** [comment]
I guess what I did doesn't follow the wished guidelines or ideas.
The abort feature is a must, IMHO.

**Comment by andyhu** [comment]
Is it already merged? How to use the proxy option?
I tried:
```js
axios.defaults.proxy = {
  host: '127.0.0.1',
  port: 8888
};
```
`127.0.0.1:8888` is Fiddler, however when I tried axios.get('http://test.com') it goes to `http://test.com:8888` and never go though the local proxy?

**Comment by nickuraltsev** [comment]
Closing as axios supports request cancellation now.

**Pull request closed without merging**
