### PR TITLE
Adding a `maxContentLength` content option

### PR DESCRIPTION
**Pull request by bomsy**
This feature fixes https://github.com/mzabriskie/axios/issues/231
Includes test

### CODE REVIEW

**Comment by bomsy** [comment]
@mzabriskie The launchers are failing to start a couple of browsers. Do you have any ideas why? Thanks.

**Comment by mzabriskie** [comment]
I will look into it

**Comment by mzabriskie** [comment]
Can you try rebasing your branch on master? I had been making changes to how tests run on Saucelabs around the same time as your PR was submitted.

**Comment by bomsy** [comment]
Seems to still fail

**Comment by bomsy** [comment]
@mzabriskie It seems to happen for other pull request. This may have to do with the version node also.

**Comment by bomsy** [comment]
@mzabriskie Hey any hope of this getting sorted out? I was hoping to help out with fixing more issues. Thanks

**Pull request closed without merging**
